NationalCookies.MVC/Models/ErrorViewModel.cs
using System;

namespace NationalCookies.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NationalCookies.MVC/Controllers/CookieController.cs
using Microsoft.AspNetCore.Mvc;
using NationalCookies.Data.Interfaces;

namespace NationalCookies.Controllers
{
    public class CookieController : Controller
    {
        private ICookieService _cookieService;

        public CookieController(ICookieService cookieService)
        {    
            _cookieService = cookieService;          
        }

        public IActionResult Index()
        {
            return View(_cookieService.GetAllCookies());
        }

        public IActionResult ClearCache()
        {
            _cookieService.ClearCache();

            return RedirectToAction("Index", "Home");
        }
    }
}

NationalCookies.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace NationalCookies.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Error()
        {          
            return View();
        }


    }
}

NationalCookies.MVC/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using NationalCookies.Data.Interfaces;

namespace NationalCookies.Controllers
{

    public class OrderController : Controller
    {
        private IOrderService _orderService;    


        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;          
        }

        public IActionResult Index()
        {
            var orders = _orderService.GetAllOrders();            

            return View(orders);
        }


        public IActionResult Detail(int id)
        {            
             var order = _orderService.GetOrderById(id);           

            return View(order);
        }

        public IActionResult CancelOrder(int id)
        {
            _orderService.CancelOrder(id);            

            return RedirectToAction("Index");
        }

        public IActionResult PlaceOrder(int id)
        {
            _orderService.PlaceOrder(id);            

            return RedirectToAction("Index");
        }

        public IActionResult AddCookieToOrderLine(int cookieId)
        {
            _orderService.AddCookieToOrder(cookieId);            

            return RedirectToAction("Index", "Order");
        }
    }
}

NationalCookies.MVC/Views/Cookie/Index.cshtml
@model List<Cookie>
@{
    ViewData["Title"] = "Cookies!";
}

<h2>Check out the awesome assortment of cookies:</h2>

@for (int i = 0; i < Model.Count; i++)
{
    if (i ==0)
    {
        @:<div class="row">
    }
    <form action="/Order/AddCookieToOrderLine" id="AddCookieToOrderLine@@@i">
      
        <input type="hidden" value="@Model[i].Id" name ="cookieId" id="cookieId" />
        <div class="col-md-2">
            <p>
                <strong>@Model[i].Name</strong>
            </p>
            <p>
                <img src="@Model[i].ImageUrl" alt="@Model[i].Name" width="110" height="110" />
            </p>
            <p>
                € @Model[i].Price.ToString(CultureInfo.CurrentCulture) / piece
            </p>
            <p><button type="submit" >Add to order</button></p>
        </div>
    </form>

    if (i % 2 == 0 && i > 0)
    {
        @:</div>
        @:<div class="row">
    }
}

NationalCookies.MVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>About this application</h2>
<h3>This is a demo application that accompanies a <a href="https://app.pluralsight.com/library/courses/microsoft-azure-cache-implementing/" target="_blank">Pluralsight</a> course</h3>

<p>This application is created as an example application to show how to create a web application that uses caching to improve performace.</p>
<p>You can find the code for this application on <a href="https://github.com/bmaluijb/NationalCookies" target="_blank">GitHub.</a></p>
<p>If you have any questions about this app, contact <a href="mailto:barry@waardedoorit.nl">barry@waardedoorit.nl</a></p>

NationalCookies.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<img src="https://intcookie.azureedge.net/cdn/cookie.jpg" alt="cookie" />

<span style="font-size:xx-large">We sell cookies in the Netherlands!</span>


<div class="row">

    <div class="col-md-4">
        <h2>Cookies!</h2>
        <ul>
            <li>We love all cookies!</li>
            <li>Chocolate Cookie,</li>
            <li>Butter Cookie,</li>
            <li>Macaroons</li>
            <li>You name it, we love them!</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>We are</h2>
        <ul>
            <li>National Cookies</li>
            <li>We sell cookies in the Netherlands</li>
            <li>(you know this is fake, right?)</li>
        </ul>
    </div>
</div>

NationalCookies.MVC/Views/Order/Detail.cshtml
@model Order
@{
    ViewData["Title"] = "Order detail";
}

@if (Model == null)
{

    <h2>No order was found.</h2>
}
else
{

    <h2>Details for order with Id @Model.Id</h2>

    <fieldset>
        <legend>Order</legend>
        Date: @Model.Date.LocalDateTime.ToString("d") <br />
        Total Price: € @Model.Price.ToString(CultureInfo.CurrentCulture) <br />
        Status: @Model.Status <br />
        @if (@Model.Status == "New")
        {
            <a href="PlaceOrder?id=@Model.Id">Place order</a><br />
        }


        <a href="CancelOrder?id=@Model.Id">Cancel order</a>

    </fieldset>

    <h3>Order lines:</h3>
    <table>
        <tr>
            <td>Cookie name</td>
            <td># cookies</td>
        </tr>
        @foreach (var line in Model.OrderLines)
        {
            <tr>
                <td>@line.Cookie.Name</td>
                <td>@line.Quantity</td>
            </tr>
        }

    </table>
}

NationalCookies.MVC/Views/Order/Index.cshtml
@model List<Order>
@{
    ViewData["Title"] = "Orders";
}


<h2>Here are your orders:</h2>

<table>
    <tr>
        <td>Order date</td>
        <td># order lines</td>
        <td>Total price</td>
        <td>Status</td>
        <td></td>
        <td></td>

    </tr>
    @foreach (var order in Model)
    {
        <tr>
            <td>@order.Date.ToLocalTime().ToString("d")</td>
            <td>@order.OrderLines.Count</td>
            <td>€ @order.Price.ToString(CultureInfo.CurrentCulture)</td>
            <td>@order.Status</td>
            <td><a href="Order/Detail?id=@order.Id" >Details</a></td>

            <td><a href="Order/CancelOrder?id=@order.Id">Cancel order</a></td>
            @if (order.Status == "New")
            {
                <td><a href="Order/PlaceOrder?id=@order.Id">Place order</a></td>
            }
        </tr>
    }

</table>

NationalCookies.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NationalCookies</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">National Cookies</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Cookie" asp-action="Index">Cookies</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Index">Orders</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NationalCookies</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>